markdown: kramdown
#theme: minima
#theme: jekyll-theme-slate
remote_theme: benbalter/retlab
title: WATE-Florida 2022
description: Workshop in Applied and Theoretical Economics
sidebar: toc
github:
  is_project_page: false
  
  plugins:
  - jekyll-remote-theme
