markdown: kramdown
theme: minima
title: WATE-Florida 2022
description: Workshop in Applied and Theoretical Economics
github:
  is_project_page: false

header_pages:
- call_for_papers.md
- accommodations.md

